### PR TITLE
docs: Add anchor description.

### PR DESCRIPTION
**Pull request by tenpaMk2**
I added the description about `anchor` of Graphic Component.
Original discussion is [#2578](https://github.com/excaliburjs/Excalibur/discussions/2578).

I found that there is no code sample using `anchor` ,
so, I added it in the sample code of `docs/04.2-graphics-component.mdx` .

This is my first pull-request!!
If something is wrong, please tell me how to solve it.

### CODE REVIEW

**Review by eonarheim — APPROVED** [review]
@tenpaMk2 This is great! Exactly what I had in mind!

Tested everything locally 👍

**Comment by eonarheim** [comment]
Should be deployed to excaliburjs.com soon

**Comment by eonarheim** [comment]
It's live! 
image

**Comment by tenpaMk2** [comment]
Thanks for deploying❗ I can see it now.

**Comment by tenpaMk2** [comment]
This is the original file of draw.io(diagrams.net).
Save if you need.
<https://www.dropbox.com/sh/j0oyeghsgxzmg49/AAC7jvuWIs5qv0C88ZEY5laia?dl=0>

**Pull request merged**
