### PR TITLE
fix: remove loader in array from game.start examples

### PR DESCRIPTION
**Pull request by chrisk-7777**

### CODE REVIEW

**Comment by chrisk-7777** [comment]
I just added one additional commit to cover the animation event being incorrect. 

Also, I noticed on the animation docs, in the sample towards the end the following is used `Util.range(1, 10)`, but I can't see that export on `Util` anymore. But the demo appears to work. Was it recently removed? 

When it comes to doc changes, should it always reflect the most recent, non-beta, release?

**Comment by eonarheim** [comment]
> Also, I noticed on the animation docs, in the sample towards the end the following is used Util.range(1, 10), but I can't see that export on Util anymore. But the demo appears to work. Was it recently removed?

Ope, this was promoted to nix the `Util`, so `ex.range(1, 10)` is the new way 👍 

> When it comes to doc changes, should it always reflect the most recent, non-beta, release?

That is our intent 👍 we usually hold unreleased feature doc changes in a branch until the main release

**Review by eonarheim — APPROVED** [review]
@chrisk-7777 Thanks again! I very much appreciate all the docs updates!

**Comment by chrisk-7777** [comment]
Gotcha, makes sense. 
Not sure what is happening with the build, I'll try to look after work tomorrow

**Comment by eonarheim** [comment]
Me neither, seems like something unrelated to your changes has gone wrong

**Comment by eonarheim** [comment]
@kamranayub Any ideas?

**Comment by eonarheim** [comment]
@chrisk-7777 I've switched around the main build, theoretically updating with the latest should fix the build🤞

**Comment by eonarheim** [comment]
@chrisk-7777 Actually, just went for the merge and it worked out 👍 Thanks again for all the docs updates!

**Comment by chrisk-7777** [comment]
Heh, what an interesting one. Thanks for getting it through

**Pull request merged**
